# Site settings
title: Export My Contacts
description: > # this means to ignore newlines until "baseurl:"
  Export contacts from Gmail, Yahoo, Outlook.com, LinkedIn, iCloud and others to CSV
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.exportmycontacts.com" # the base hostname & protocol for your site

cloudsponge_key: f37c1326177a11193ced84e4a22f6cd3f82f8497

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["autolink"]
